# Generated by Django 5.0.4 on 2025-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
                ("enable", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the permission",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL pattern this permission applies to",
                        max_length=255,
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        help_text="Regular expression pattern for URL matching",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this permission allows",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "indexes": [
                    models.Index(fields=["name"], name="permissions_name_6a4248_idx"),
                    models.Index(fields=["url"], name="permissions_url_5fa3f8_idx"),
                ],
            },
        ),
    ]
